### ISSUE TITLE
ERROR Sample: T.me/CryptoVIPSignalTA

### ISSUE THREAD

**Issue by TypeCrypto** [zamgi/lingvo--UrlDetector#1]
Don't miss out one of the biggest giveaway. Join the bot and get your referral link. Share it with your friends and family or on your social media networks. You can track the top refferal chart and see where you stand. The first price is $3000 and every member rank between 11-50 will get $50. Don't miss this one you still have a lot of time. Keep earning😊
 T.me/CryptoVIPSignalTA

http://url.apphb.com/index.html
Process the text and return: Url and E-mail addresses not found in the text

**But T.me/CryptoVIPSignalTA is url**

![20210410052636](https://user-images.githubusercontent.com/80462555/114242368-5c386300-99bd-11eb-800e-1bff0f5b1f48.png)

**Comment by zamgi** [comment]
you can just append missing first level domains ("me") to resource file "url-detector-resources.xml/url-detector-resources/first-level-domains"
